// import './globals.css';

import { LogoImage, Navbar, UserInfo } from "@/components";

export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Navbar bgStyle="solid" left={<LogoImage />} right={<UserInfo />} />
      {children}
    </div>
  );
}
