// import './globals.css';

import { OBANavbar } from "@/components";

export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: // devMode,
{
  children: React.ReactNode;
}) {
  return (
    <div>
      <OBANavbar />
      {children}
    </div>
  );
}
